"""Add reported field

Revision ID: e1e19497e31f
Revises: c3f1d3ab34d2
Create Date: 2026-05-06 19:40:23.923015

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e1e19497e31f"
down_revision: str | Sequence[str] | None = "c3f1d3ab34d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "reported",
                sa.Boolean(),
                nullable=False,
                server_default="FALSE",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.drop_column("reported")

    # ### end Alembic commands ###
