# Override over compose.yaml
services:
  # Сервис сервера
  test-site:
    ports: !reset []

  # Nginx сервер
  nginx:
    image: nginx:stable
    container_name: test-site-nginx
    restart: always

    depends_on:
      - test-site

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/test-site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

    networks:
      - server-network
